<a href="https://colab.research.google.com/github/Marion-Moraa/Marion-Moraa/blob/main/Data_Preparation_Practical.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#importing module
import pandas as pd

In [4]:
#Uploading the dataset
from google.colab import files
uploaded = files.upload()

Saving sales_data_dirty.csv to sales_data_dirty.csv

In [5]:
#Load the dataset
data = pd.read_csv("sales_data_dirty.csv")

In [6]:
#View the data
data.head() #Displays rows of the dataset, by default displays the first five rows of the dataset

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Region,PaymentMethod
0,1001,John Kamau,Laptop,Electronics,2,75000,05/01/2025,Nairobi,Mpesa
1,1002,Mary Wanjiku,Mouse,Electronics,5,1500,05/01/2025,Nakuru,M-Pesa
2,1003,Peter Otieno,Keyboard,Electronics,NaN,2500,06/01/2025,Kisumu,Cash
3,1004,Amina Hassan,Office Chair,Furniture,1,12000,07/01/2025,Mombasa,Card
4,1005,David Mwangi,Desk,Furniture,Two,30000,08/01/2025,Nairobi,Mpesa

In [7]:
# Check Dataset structure
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   OrderID        20 non-null     int64
 1   CustomerName   19 non-null     object
 2   Product        20 non-null     object
 3   Category       20 non-null     object
 4   Quantity       19 non-null     object
 5   Price          19 non-null     object
 6   OrderDate      19 non-null     object
 7   Region         19 non-null     object
 8   PaymentMethod  20 non-null     object
dtypes: int64(1), object(8)
memory usage: 1.5+ KB
None

In [8]:
#Investigate the Dataset by running the following commands
data.describe() #gives a quick statistical overview of the dataset's numeric columns

          OrderID
count    20.00000
mean   1010.50000
std       5.91608
min    1001.00000
25%    1005.75000
50%    1010.50000
75%    1015.25000
max    1020.00000

In [9]:
data.isnull() #Checks every cell in the dataset, if a value is missing, it returns True
#if it exists, it returns False

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Region,PaymentMethod
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,True,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False
7,False,True,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,True,False,False,False
14,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,True,False,False
16,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,True,False
18,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False

In [10]:
data.isnull().sum() # sum() counts how many True values exist, the missing values
#in each column

OrderID          0
CustomerName     1
Product          0
Category         0
Quantity         1
Price            1
OrderDate        1
Region           1
PaymentMethod    0
dtype: int64

In [11]:
data.duplicated() #Finds all duplicate values in the dataset, checks each row
#if the row already appeared earlier, it returns True
#if it's the first time the row appears, it returns False

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
dtype: bool

In [12]:
data.duplicated().sum() #.sum() counts the number of True values

np.int64(0)

In [13]:
# Identifying Inconsistent labels
data["Category"].unique()
#data["Category"] selects only the Category column from the dataset.
#the function unique() finds all distinct values in that column, it removes
#duplicates and shows each value only once.

array(['Electronics', 'Furniture', 'Furn.', 'electronic'], dtype=object)

In [14]:
#Check Payment Method Inconsistencies
data["PaymentMethod"].unique()

array(['Mpesa', 'M-Pesa', 'Cash', 'Card'], dtype=object)

In [15]:
#Identify Datatype Problems
data["Quantity"].unique()

array(['2', '5', nan, '1', 'Two', '3', '4', '-1', 'four'], dtype=object)

In [16]:
data["Price"].unique()

array(['75000', '1500', '2500', '12000', '30000', 'KES 70000', '18000',
       '15000', '28000', '1400', '72000', nan, '71000'], dtype=object)

In [19]:
#Check invalid dates
data["OrderDate"].unique()

array(['05/01/2025', '06/01/2025', '07/01/2025', '08/01/2025',
       '09/01/2025', '10/01/2025', '11/01/2025', '12/01/2025',
       '13/01/2025', '14/01/2025', nan, '2025-13-01', '15/01/2025',
       '16/01/2025'], dtype=object)

In [20]:
#Missing region
data["Region"].isnull().sum()

np.int64(1)

In [21]:
#Find rows with negative quantity
# First, convert 'Quantity' to numeric, coercing errors to NaN
data['Quantity_numeric'] = pd.to_numeric(data['Quantity'], errors='coerce')
# Now, filter for rows where 'Quantity_numeric' is less than 0
data[data['Quantity_numeric'] < 0]

TypeError: '<' not supported between instances of 'str' and 'int'